"""add job fields and job_logs table

Revision ID: 38ab3a3e044b
Revises: c717350d943a
Create Date: 2026-09-10 00:04:33.959883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38ab3a3e044b'
down_revision: Union[str, None] = 'c717350d943a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('task_type', sa.String(length=100), nullable=False))
    op.add_column('jobs', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('jobs', sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_job_owner_idempotency_key', 'jobs', ['created_by_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_owner_idempotency_key', 'jobs', type_='unique')
    op.drop_column('jobs', 'idempotency_key')
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'result')
    op.drop_column('jobs', 'payload')
    op.drop_column('jobs', 'task_type')
    # ### end Alembic commands ###
