"""add composite index for job cursor pagination

Revision ID: 43cb686e71ec
Revises: f64f08b68003
Create Date: 2026-09-11 10:02:00.179699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43cb686e71ec'
down_revision: Union[str, None] = 'f64f08b68003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobs_created_by_created_at_id', 'jobs', ['created_by_id', 'created_at', 'id'], unique=False, postgresql_ops={'created_at': 'DESC', 'id': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_created_by_created_at_id', table_name='jobs', postgresql_ops={'created_at': 'DESC', 'id': 'DESC'})
    # ### end Alembic commands ###
